pipeline
  publish:
    image: plugins/docker
    repo: gboo/docker-nvidia
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
